### PR TITLE
Improve copy UX on bs4_book (#1040)

### PR DESCRIPTION
**Pull request by keithmcnulty**
Improves ux of copy to clipboard:

1.  Copy only appears on input code blocks
2.  Only on mouseover
3.  Copy button remains fixed during scroll
4.  Copy button repositioned marginally for better look on single code lines

### CODE REVIEW

**Comment by apreshill** [comment]
Hi @keithmcnulty - thank you so much for this PR! We've gotten feedback that the button only being present on hover is confusing for users. Our technical writer actually missed the feature altogether b/c they didn't hover over the code block exactly. Would you be open to showing it by default but adding some opacity to it, then darkening upon hover? For example:

Screen Shot 2021-06-03 at 3 51 25 PM

**Comment by keithmcnulty** [comment]
> Hi @keithmcnulty - thank you so much for this PR! We've gotten feedback that the button only being present on hover is confusing for users. Our technical writer actually missed the feature altogether b/c they didn't hover over the code block exactly. Would you be open to showing it by default but fading it (by adding some opacity), then darkening upon hover? For example:
> 
> Screen Shot 2021-06-03 at 3 51 25 PM

Hi @apreshill - I think that sounds reasonable.  Although I think it’s important for a less obtrusive user experience only to enable this feature on input code chunks and not on output chunks.  Would you like me to adjust the PR to reflect or is someone handling this on the RStudio side?   Thanks!

**Comment by apreshill** [comment]
Thank you @keithmcnulty I'll ask around and respond here when I hear back.

**Comment by cderv** [comment]
See https://github.com/rstudio/bookdown/issues/1040#issuecomment-874993960

We've done several improvement in several smaller PR that we have now merged. Please have a look ! 

This PR is now outdated but we are interesting by your feedback on the changes. Thank you!

**Comment by cderv** [comment]
This PR is outdated by several others following discussion in #1040

Thanks @keithmcnulty !

**Pull request closed without merging**
