### PR TITLE
Fixes #60

### LINKED ISSUE #60: default HTML output on iPad
Hi @yihui 
When browsing the standard HTML output from bookdown on an iPad, there doesn't seem to be a way to collapse the sidebar containing the table of contents.  So, when reading the bookdown or r4ds websites, the sidebar always takes up over 1/3 of the reading space on the iPad.  It would be great if the default HTML output allowed one to collapse/expand the TOC, or to see TOC in a menu.

Thanks
Kyle

### PR DESCRIPTION
**Pull request by dataopt**

### CODE REVIEW

**Comment by dataopt** [comment]
I tested my books on a second-generation iPad mini running iOS 9, Firefox 59 on Mac and Windows 8.1, Safari on Mac, and IE 11 on Windows 8.1.

**Comment by yihui** [comment]
Unfortunately the fix is probably not this simple. The `fixed` class was added to the book body for reasons. I don't remember all reasons now, but at least anchors won't work correctly without the `fixed` class (as in your fix)., e.g., currently they work correctly:

- https://bookdown.org/yihui/bookdown-demo/intro.html#fig:nice-fig
- https://bookdown.org/yihui/bookdown-demo/intro.html#tab:nice-tab

After your fix, they won't point to the expected elements (figure/table) on the page. The relevant CSS should be:
https://github.com/rstudio/bookdown/blob/b1b37d3d4bd4299f6103065d5d83c07307d9468c/inst/resources/gitbook/css/plugin-bookdown.css#L43-L45

**Comment by dataopt** [comment]
So body-inner is getting in the way?  Would making it transparent work?

**Comment by yihui** [comment]
I suspect this is a rather tricky issue specific to iPads. The fixed toolbar works fine on my iPhone (Safari).

**Comment by dataopt** [comment]
This is too mysterious.  So it's not a webkit bug.

**Comment by dataopt** [comment]
I found the root cause.  It's in the template `gitbook.html`.

**Pull request closed without merging**
