### PR TITLE
bs4_book: no scroll on x overflow and correct copy btn placement

### LINKED ISSUE #1086: Copy copy button fix
https://github.com/r-lib/pkgdown/commit/3574fe0aef12da059875896f5ca21f508aecaefe

### PR DESCRIPTION
**Pull request by maelle**
Fix #1086

Also related #1040 (currently the copy-code button might _hide_ some code)

### CODE REVIEW

**Review by cderv — APPROVED** [review]
Great. Can you add NEWS bullet so that we track the different changes ? 

I will triage and merge the different bs4_book() items at the end before release to make a single big part on all the changes. Thanks!

**Comment by maelle** [comment]
I'm not sure this should be merged as this can hide text, though?

**Comment by maelle** [comment]
image

**Comment by cderv** [comment]
Thanks. I see. 

This is an issue because we show the copy button always, with no opacity. It would probably no be an issue if the button was shown on hover only (like in `gitbook()`)

This is a topic that we are still thinking about (#1040 and associated PR #1041). 

Best is to deal with this PR when we will deal with the other.

**Comment by maelle** [comment]
Solution I put together with DevTools:

* Put the copy div right at the beginning of the pre node. (prepending instead of appending)
* CSS

```css
pre .copy {
float: right;
margin-left: 1rem;
margin-bottom: 1rem;
}

```

**Comment by maelle** [comment]
image

**Comment by cderv** [comment]
FWIW, quarto as a smaller icon and deal with this by having a padding for the pre block, leaving space between the code part and pre background for the icon 

````css
pre.sourceCode.code-with-copy {
    padding-right: 25px;
}
````
image

This leave the code aligned the same way on the right side.

**Comment by cderv** [comment]
with gitbook() the icon is right above the text in the margin
image

**Comment by cderv** [comment]
@apreshill we should look into that in the same bundle as the copy button improvement, and uniformisation between outputs. 

What are your thoughts on this ?

**Comment by apreshill** [comment]
Hi @cderv looking into this right now. Also another point of comparison is GitHub's new copy icon UI: 

https://github.com/apreshill/bs4booktesting/issues/1

Looks like they actually do the scrolling underneath the button on hover.

I like the padding-right idea, but needed to add 60px to clear the button instead of 25px. Here is how that looks: 
https://apreshill.github.io/bs4booktesting/

Screen Shot 2021-06-30 at 10 30 22 AM


I wish the padding could be a bit more narrow.

---

Using this space to think out loud here:

1. I'd like to keep the existing behavior of permanent copy button (no reveal just on hover). I think that makes sense for a book output, and is more friendly to readers who may not be programmers.
2. @hadley might you be open to switching to an icon here? That would decrease the padding needed. We could follow Quarto's lead and use the Bootstrap clipboard icon: https://icons.getbootstrap.com/icons/clipboard/ (maybe switching to this icon after click: https://icons.getbootstrap.com/icons/clipboard-check/). If you want to keep the word copy, I'll try a few more CSS possibilities.

**Comment by hadley** [comment]
I think it makes sense to match quarto here; I'm fine with the icon.

**Comment by cderv** [comment]
This branch is now tested in https://cderv.github.io/bs4booktesting/wrap-and-scroll/

and it's look like this 
image

Current master looks like this: https://cderv.github.io/bs4booktesting/

image


So this PR: 

* Wraps the content to not have scroll
* make the copy button not hide code by having the text be "around". For reference, the other solution would be a margin for the copy button in the code block : https://github.com/rstudio/bookdown/pull/1187#issuecomment-871607714

@apreshill to discuss.

**Pull request merged**
