### PR TITLE
fix the bug that multi-byte character in R code throw error

### PR DESCRIPTION
**Pull request by gitzhuoer**
You may refer https://github.com/viking/r-yaml/issues/38 for more information. I have send e-mails to you about this issue @yihui

### CODE REVIEW

**Comment by gitzhuoer** [comment]
---
    title: "minimal example for multi-byte character in R code"
    ---


    Taking From https://github.com/hadley/r4ds 's `workflow-basics.Rmd` `## Practice`

    ```{r include=FALSE, cache=FALSE}
    knitr::opts_chunk$set(cache = TRUE)
    ```

    1.  Why does this code not work?

        ```{r, error = TRUE}
        my_variable <- 10
        my_varable
        ```
        
        Look carefully! (This may seem like an exercise in pointlessness, but
        training your brain to notice even the tiniest difference will pay off
        when programming.)

**Comment by gitzhuoer** [comment]
Above is a minimal reproducible example. After you save the content as `index.Rmd` in UTF-8.

**Comment by gitzhuoer** [comment]
Both errors occur due to passing `encoding = "UTF-8"` to `rmarkdown::render()`.

**Comment by gitzhuoer** [comment]
Maybe `"native.enc"` is better than `getOption("encoding")`. Anyway, the encoding problem on Windows is really, really, and really hard to eradicate.

**Comment by yihui** [comment]
Is your Rmd encoded in UTF-8? https://bookdown.org/yihui/bookdown/usage.html

**Comment by gitzhuoer** [comment]
Yes. But please write a moment. Just now I find that my Pull request would cause error when the text containes multi-byte character.

**Comment by gitzhuoer** [comment]
`index.Rmd`:

    ---
    title: "minimal example for multi-byte character in R code"
    ---

    ı

    Taking From https://github.com/hadley/r4ds 's `workflow-basics.Rmd` `## Practice`

    ```{r include=FALSE, cache=FALSE}
    knitr::opts_chunk$set(cache = TRUE)
    ```

    1.  Why does this code not work?

        ```{r, error = TRUE}
        my_variable <- 10
        my_varıable
        print('ı')
        ```
        
        Look carefully! (This may seem like an exercise in pointlessness, but
        training your brain to notice even the tiniest difference will pay off
        when programming.)

```r
rmarkdown::render('index.Rmd', encoding = 'native.enc')
```

image

**Comment by gitzhuoer** [comment]
Aha. I find a (possible) soultion.

**Comment by gitzhuoer** [comment]
Sorry to disturb you. I create a new Pull request https://github.com/rstudio/bookdown/pull/432

**Pull request closed without merging**
