### PR TITLE
add number_sections argument to markdown_document2 (closes #756)

### LINKED ISSUE #756: Would you mind developing word_book() output format?
I was wondering if there would be any way that someone could develop `bookdown::word_book()` output format just like either `bookdown::pdf_book()` or `bookdown::html_book()`.
Currently, figure and table numbering does not follow chapter hierarchy when output type is `bookdown::word_document2()`, which means a figure inserted under Chapter 3 is numbered Figure 1 (not Figure 3.1) if that figure is the first one throughout all Rmds. This happens to table numbering as well.
It would be so much appreciated if `word_book()` format could be implemented.
Many thanks!

### PR DESCRIPTION
**Pull request by atusy**
Please merge after https://github.com/rstudio/rmarkdown/pull/1879

This PR adds number_sections argument to `markdown_document2` and its family (e.g., `word_document2`).

I set `TRUE` as a default value to be consistent with other formats (e.g., `html_document2`).
However, this may not be a good idea in case users' Rmd files manually numbered sections...

### CODE REVIEW

**Review by yihui — APPROVED** [review]
@atusy Thanks!

@cderv Feel free to merge this one after rstudio/rmarkdown#1879 is merged.

**Comment by cderv** [comment]
LGTM. 

Only one think: This feature relies on newer rmarkdown. So I did this 7f5af9c which is what to do in my experience. 
@yihui do you work that way or have you another process for this ? Waiting for you answer before merging. 

And we don't see this because ... we don't correctly test IMO. Once again, I think we should add test each time we add something. For now, I don't think the current test suite in bookdown allow to easily add test for this, so I'll do it later.

**Comment by cderv** [comment]
It is not a perfect way to do it but I added a quick test because that is better to have one.

**Review by yihui — APPROVED** [review]
@cderv 7f5af9c looks good to me. Yes, we should use `Remotes` in `DESCRIPTION` when it requires a Github version of a package. Thanks!

**Comment by atusy** [comment]
@cderv Thanks for changes!

**Comment by cderv** [comment]
Thanks a lot @atusy !

**Pull request merged**
