### PR TITLE
Add Exercise and Solution to included theorem/proof environments

### PR DESCRIPTION
**Pull request by dshuman1**
Exercise falls under the Definition category. Solution falls under the Proof category. I suspect these will be of widespread interest to authors writing activities and solutions. I was not sure how to test these changes. Considered adding an additional activity/solution example to 02-components.Rmd, but did not do so.

### CODE REVIEW

**Comment by endri81** [comment]
I installed latest bookdown using `devtools::install_github('rstudio/bookdown')`. First it worked just fine but now I am getting error message :

> 1: In get_engine(options$engine) :
>   Unknown language engine 'exercise' (must be registered via knit_engines$set()).
> 2: In get_engine(options$engine) :
>   Unknown language engine 'solution' (must be registered via knit_engines$set()).

**Comment by dshuman1** [comment]
This is an outstanding pull request that has not yet been merged into the latest version of bookdown. So the exercise and solution options are not yet available.

**Comment by endri81** [comment]
@dshuman1 That's too bad. I think that your add-ons are really needed. Thank you for your efforts and contribution.

**Comment by yihui** [comment]
Thanks for your contribution!

**Comment by yihui** [comment]
@dshuman1 Actually could you also add simple examples in Chapter 2? https://github.com/rstudio/bookdown/blob/master/inst/examples/02-components.Rmd

**Comment by dshuman1** [comment]
OK, I will do this and submit another pull request.

**Pull request merged**
