### PR TITLE
`bs4_book()`: Fix alignment of text blocks within rmdnote divs

### LINKED ISSUE #1084: Code block in rmdnote needs margins adjusted
e.g.

Screenshot 2021-02-22 at 7 32 37 AM

Code should occupy full width of block

### PR DESCRIPTION
**Pull request by maelle**
Fix #1084 (if I understood the problem correctly)

### CODE REVIEW

**Review by cderv — COMMENTED** [review]
This will reduce the pre background and code won't be aligned anymore with the outside text

From the issue, 
> Code should occupy full width of block

Do we want either the opposite and get the pre background to be aligned with the other pre background outside of `rmdnote` box ? 

To illustrate the above, with this PR here is what it looks like:
image

Code and text in the box are no more aligned which does not feel right to me.

Is the screenshot posted in #1084 what it should look like ? Because it seems that the link in mastering-shiny already looks like that.

**Comment by maelle** [comment]
> Because it seems that the link in mastering-shiny already looks like that.

Yes I guess I do not understand what the issue is.

**Comment by cderv** [comment]
@maelle see answer in https://github.com/rstudio/bookdown/issues/1084#issuecomment-860937264

> Like how code blocks on a narrow page occupy the full width of the column, **the code block within a note should also occupy the full width (i.e. no gap between left and right side of code block and containing border)**. Does that make sense? It's not easy to describe in words.

So this PR is not yet quite right. Do you have time to change or should I do this ?

**Comment by cderv** [comment]
cc @apreshill as we discussed it yesterday.

**Comment by maelle** [comment]
image

Btw whilst looking at this on different screen sizes it made the need for a copy-button fix (to not make it hide code) look even more important. :grimacing:

**Comment by cderv** [comment]
I think I would keep the code content align with the text content even if we make the background full width 

It would look like this 
image

**Comment by cderv** [comment]
what is your feeling on this one @apreshill ? I'll tweak the implementation following what we decide. 
Thanks @maelle !

**Comment by apreshill** [comment]
I agree @cderv - I tend to prefer keeping the text aligned inside the note box.

**Comment by cderv** [comment]
So background full width and text align it will be! Thanks.

**Comment by cderv** [comment]
This will now look like this
image

**Review by apreshill — APPROVED** [review]
LGTM- thanks!

**Pull request merged**
