### PR TITLE
Change to 1st Para., Acknowledgemetns index.Rmd

### PR DESCRIPTION
**Pull request by mlamias**
Added "with" on second to last sentence on First Paragraph of Acknowledgements section.

### CODE REVIEW

**Comment by yihui** [comment]
Why did you close it? It seems there should be a `with` indeed.

**Comment by mlamias** [comment]
Oh, Sorry, Yihui.  I didn't mean to.  I will fix this again 
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Yihui Xie <notifications@github.com> Date: 1/12/17  3:58 PM  (GMT-05:00) To: rstudio/bookdown <bookdown@noreply.github.com> Cc: mlamias <mlamias@yahoo.com>, State change <state_change@noreply.github.com> Subject: Re: [rstudio/bookdown] Change to 1st Para., Acknowledgemetns index.Rmd (#297) 
Why did you close it? It seems there should be a with indeed.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rstudio/bookdown","title":"rstudio/bookdown","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rstudio/bookdown"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yihui in #297: Why did you close it? It seems there should be a `with` indeed."}],"action":{"name":"View Pull Request","url":"https://github.com/rstudio/bookdown/pull/297#issuecomment-272281517"}}}

**Comment by yihui** [comment]
No worries. I just reopened the pull request and merged it. Thanks!

**Comment by mlamias** [comment]
Ok.  Great.  By the way, how are things? 
You have no idea how much easier you are making my thesis with Dr. Koehler with knitr and bookdown!  We sure miss you at Iowa State!!


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Yihui Xie <notifications@github.com> Date: 1/12/17  9:25 PM  (GMT-05:00) To: rstudio/bookdown <bookdown@noreply.github.com> Cc: mlamias <mlamias@yahoo.com>, State change <state_change@noreply.github.com> Subject: Re: [rstudio/bookdown] Change to 1st Para., Acknowledgemetns index.Rmd (#297) 
No worries. I just reopened the pull request and merged it. Thanks!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rstudio/bookdown","title":"rstudio/bookdown","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rstudio/bookdown"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yihui in #297: No worries. I just reopened the pull request and merged it. Thanks!"}],"action":{"name":"View Pull Request","url":"https://github.com/rstudio/bookdown/pull/297#issuecomment-272344346"}}}

**Comment by yihui** [comment]
Ah, I did not realize who you were until I saw your email address, since your Github profile does not have much information. Anyway, I'm very glad to hear it helped you with your thesis. Making it easier to write thesis is certainly an important goal of bookdown, and I'm also hoping a certain professor can write a book using bookdown. My only regret is I did not start the bookdown project earlier :)

I'm in the Omaha area now -- not too far away from Ames. So feel free to drop by anytime you like and stay however long you want, although we don't have anything particularly interesting here except the zoo.

**Pull request merged**
