### PR TITLE
bs4_book: make it possible to override CSS?

### PR DESCRIPTION
**Pull request by maelle**
Related to #1016 as I was trying to add a quick tweak to my own book.

Or if all tweaks are supposed to be made via the theme argument, maybe the css argument of bs4_book (in the ... ) should be somehow coupled with warning message? (I realize forbidden might be too much as I use the css argument myself for print styles :grin:)

Cc @hadley

### CODE REVIEW

**Comment by hadley** [comment]
How are you supplying this argument?

**Comment by maelle** [comment]
It was in the css argument, I had written it in the `_output.yml` config.

I had

```yml
bookdown::bs4_book:
  theme:
    primary: "#1f58a3"
    yellow: "#804600"
  includes:
    before_body: WIP.html
  css: style.css
```

Now I have

```yml
bookdown::bs4_book:
  theme:
    primary: "#1f58a3"
    yellow: "#804600"
    h4-font-size: "1.1rem"
  includes:
    before_body: WIP.html
```

which seems more correct of course given my tweak could be made with a bootstrap variable. However, when using the CSS file, I was expecting it'd be loaded after the other stylesheets.

**Comment by hadley** [comment]
Ah makes sense. As you work on this, any documentation improvements to `bs4_book()` would also be appreciated 😄 We should probably add a "Customising" section to the topic.

**Comment by maelle** [comment]
Just a note that I see some overlap (in concepts) with https://rstudio.github.io/distill/website.html#theming since it also uses variables.

**Pull request merged**
