### PR TITLE
bs4_book: Copy button uses an icon instead of text

### PR DESCRIPTION
**Pull request by cderv**
@apreshill as discussed. 

I have used the same logic as Quarto, with icon built in (using inline svg). I have looked at the code there, and reuse part of it

I have kept the style of `bs4_book()` though, with the tooltip and background, and just change the text by an icon, which changes in click for a few seconds.

Example: https://cderv.github.io/bs4booktesting/icon-copy-btn/

We need to deal with the overlap discussed in #1187 (this PR could replace the other or complement only)

### CODE REVIEW

**Comment by apreshill** [comment]
Here is what I'm thinking, will change the css to:

+ remove the border always
+ remove the background color always

I think this will address issue #1040 pretty well.

**Comment by cderv** [comment]
So something like this ? 
image

**Review by apreshill — APPROVED** [review]
I really like how this looks and works- thank you! Are you thinking we would tackle the text/icon overlap in a separate PR?

**Comment by cderv** [comment]
> Are you thinking we would tackle the text/icon overlap in a separate PR?

Yes in #1187 after merging this and updating the PR. Keeping things separate in smaller PR seems better to me in order to change the different things on the copy button.

@hadley does this icon and behavior looks ok to you ? 
I prefer to check before merging as this would change the look of your books (which build on bookdown dev version I recall).

**Comment by hadley** [comment]
LGTM

**Pull request merged**
