### PR TITLE
❇️ add `fuse` search support more language

### PR DESCRIPTION
**Pull request by Shuliyey**
# Overview

🚧  add `fuse.js` search support more language (e.g `Russian`, `Greek`, `Arabic`, `Chinese` and etc)
# Testing

image

https://user-images.githubusercontent.com/4773348/122410051-f40e8a80-cfc6-11eb-93e3-3bdfd58bde38.mp4

# Todo

- [X] in `_output.yml` add support specifying custom search library (default: `lunr`, options: [`lunr`, `fuse`])
```yaml
bookdown::gitbook:
  config:
    search:
      engine <engine, options: ['lunr', 'fuse'], default: 'lunr'>
      opts: # options to control/tune search engine behaviour (default: null)
        <k1>: <v1>
        <k2>: <v2>
         ...
```
- [X] testing down with below `_output.yaml`
```
bookdown::gitbook:
  config:
    search:
      engine: fuse
```

### CODE REVIEW

**Comment by Shuliyey** [comment]
good morning

i've tested the PR's change against below `_output.yaml`

```yaml
bookdown::gitbook:
  config:
    search:
      engine: fuse
```

was able to get positive results, although fuse.js have some fuzzy partial matching behaviours, this resulted in more returned results (i trid tuning with the options in https://fusejs.io/api/options.html, `threshold: 1` gave better returns, however there're still some partial matched page that's returned)

as an example https://fusejs.io/demo.html

list.json is
```json
[
  {
    "title": "5.2 2021-03-07 5.2.1 WSL (Windows Subsystem Linux) g++ protobuf (grpc) 编译问题 (undefined reference to “google::…”) 碰倒奇怪的g++ protobuf (grpc) 程序编译问题 g++ 版本 [甲] in ~ λ g++ --version g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 Copyright (C) 2019 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. protoc 版本 protobuffers_demo/src/cpp ▶ protoc --version libprotoc 3.6.1 编译报错 undefined reference to \google::protobuff::xxxx::…..’` # g++ [options] file... g++ -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer protobuffers_demo/src/cpp ▶ g++ -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer /usr/bin/ld: /tmp/cc8nNte2.o: in function `Company::set_name(char const*)&#39;: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x7d): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x202): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x211): undefined reference to `google::protobuf::internal::LogMessage::operator&lt;&lt;(char const*)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x21e): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&amp;)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x226): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x2cd): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()&#39; /usr/bin/ld: /tmp/cc8nNte2.o: in function `Company::set_description(char const*)&#39;: create_protobuffer.cpp:(.text._ZN7Company15set_descriptionEPKc[_ZN7Company15set_descriptionEPKc]+0x7d): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company15set_descriptionEPKc[_ZN7Company15set_descriptionEPKc]+0x202): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)&#39; ... /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x60): undefined reference to `google::protobuf::Message::CheckTypeAndMergeFrom(google::protobuf::MessageLite const&amp;)&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x80): undefined reference to `google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char*) const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0xb0): undefined reference to `google::protobuf::Message::DiscardUnknownFields()&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0xb8): undefined reference to `google::protobuf::Message::SpaceUsedLong() const&#39; /usr/bin/ld: company.pb.o:(.data.rel+0x10): undefined reference to `protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp&#39; collect2: error: ld returned 1 exit status 查询网络资料 https://zhuanlan.zhihu.com/p/305974542 提到 如果没有加上-lprotobuf 会报以下错误 project.pb.cc:(.text+0x5fc): undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)&#39; project.pb.cc:(.text+0x723): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)&#39; project.pb.cc:(.text+0x7b5): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)&#39; project.pb.cc:(.text+0x849): undefined reference to `google::protobuf::internal::WireFormat::SkipField(google::protobuf::io::CodedInputStream*, unsigned int, google::protobuf::UnknownFieldSet*)&#39; /tmp/cc1U6w5J.o: In function `Account::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const&#39;: project.pb.cc:(.text+0x8eb): undefined reference to `google::protobuf::internal::WireFormatLite::WriteUInt64(int, unsigned long, google::protobuf::io::CodedOutputStream*) 可是 -lprotobuf 有作为参数传给 g++, 那么问题在哪呢，经过排查调整 g++ 参数顺序与位置的以下方法解决了问题 (暂时不清楚为何，大概率和g++ 处理参数顺序有关) g++ 参数顺序/位置调整: g++ [options] file... → g++ file... [options] # g++ file... [options] g++ create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread protobuffers_demo/src/cpp ▶ g++ base64.o company.pb.o create_protobuffer.cpp -o create_protobuffer -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread protobuffers_demo/src/cpp ▶ ls Makefile base64.o company.pb.o create_protobuffer create_protobuffer.cpp protos read_protobuffer.cpp third_parties"
  },
  {
    "title": " 5.3 2021-03-08 5.3.1 WSL (Windows Subsystem Linux) cargo 指令 file permission 报错 WSL 跑 cargo 指令时 (比如cargo build, cargo run) 碰到 file permission 报错 $ cargo build ... warning: Error finalizing incremental compilation session directory `/mnt/c/Users/zicog/conq-ws/target/debug/incremental/conq_ws_server-2q1bffu1vnc1a/s-fq0xl8u26v-4gktak-working`: Permission denied (os error 13) warning: 2 warnings emitted warning: Error finalizing incremental compilation session directory `/mnt/c/Users/zicog/conq-ws/target/debug/incremental/conq_ws_client_cli-nqj4wzo9q5jf/s-fq0xl8tdgv-vzck31-working`: Permission denied (os error 13) warning: 1 warning emitted Finished dev [unoptimized + debuginfo] target(s) in 0.26s 以上是此链接 https://users.rust-lang.org/t/strange-cargo-build-file-permission-warnings/46980 提到的报错 解决方案升级 WSL 到 WSL2 (官方文档 https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps) 后不再报错 自动升级 wsl --install 需要加入微软 Windows Insider Program, 这里简单讲解手动升级 确保 Microsoft-Windows-Subsystem-Linux VirtualMachinePlatform 已被启动 (跑dism 命令需以管理员身份跑) dism.exe /Online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux dism.exe /Online /Get-FeatureInfo /FeatureName:VirtualMachinePlatform 如看到 状态 : 已启用 相关信息则已被启用 (如下) PS C:\Users\老叶&gt; dism /Online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux 部署映像服务和管理工具 版本: 10.0.18362.1379 映像版本: 10.0.18363.1440 功能信息: 功能名称 : Microsoft-Windows-Subsystem-Linux 显示名称 : 适用于 Linux 的 Windows 子系统 描述 : 为 Windows 上运行的本机用户模式 Linux shell 和工具提供服务和环境。 需要重新启动 : Possible 状态 : 已启用 自定义属性: ServerComponent\Description : 提供服务和环境以在 Windows 上运行本机用户模式 Linux shell 和工具。 ServerComponent\DisplayName : 适用于 Linux 的 Windows 子系统 ServerComponent\Id : 1033 ServerComponent\Type : Feature ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux 操作成功完成。 PS C:\Users\老叶&gt; dism.exe /Online /Get-FeatureInfo /FeatureName:VirtualMachinePlatform 部署映像服务和管理工具 版本: 10.0.18362.1379 映像版本: 10.0.18363.1440 功能信息: 功能名称 : VirtualMachinePlatform 显示名称 : 虚拟机平台 描述 : 为虚拟机启用平台支持 需要重新启动 : Possible 状态 : 已启用 自定义属性: (没有找到任何自定义属性) 否则需启动 Microsoft-Windows-Subsystem-Linux VirtualMachinePlatform (注 VirtualMachinePlatform 需要在 BIOS 里启用 CPU VT-x 或相关类似虚拟功能 参考资料 https://techsviewer.com/enable-intel-virtualization-technology-vt-x-bios/) dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart 或者通过搜索 Windows Feature 启用 适用于 Linux 的 Windows 子系统 虚拟机平台 安装成功后重启系统 安装 WSL2 Linux Kernal 内核 下载地址 https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi Invoke-WebRequest https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi -OutFile $HOME\wsl_update_x64.msi msiexec /i $HOME\wsl_update_x64.msi /qf 设置默认 wsl 版本为2 wsl --set--default-version 2 新安装wsl Linux 版本 会默认为 WSL2, 以下讲解升级已安装 wsl 版本 到WSL2 检查已安装wsl, 这里需升级的 WSL 是 Ubuntu wsl -l -v PS C:\Users\老叶&gt; wsl -l -v NAME STATE VERSION * Ubuntu Running 1 设wsl Ubuntu 版本为2 (以下命令迁移过程会花些时间) wsl --set-version Ubuntu 2 再次检查 wsl Ubuntu 版本是否升级后为2 PS C:\Users\老叶&gt; wsl -l -v NAME STATE VERSION * Ubuntu Running 2 Alpine Running 2 登录 WSL2 Ubuntu, 再次尝试 cargo 相关指令 将不再有 file permission 相关报错 PS C:\Users\老叶&gt; wsl -d Ubuntu [oh-my-zsh] Random theme &#39;bira&#39; loaded ╭─xxx@xxx /mnt/c/Users/老叶 ╰─$ cd ╭─xxx@DY-PC ~ ╰─$ cd c++/protobuffers_demo/src/rust/read-protobuffer ╭─xxx@xxx ~/c++/protobuffers_demo/src/rust/read-protobuffer ‹master*› ╰─$ cargo run Finished dev [unoptimized + debuginfo] target(s) in 0.00s Running `target/debug/read-protobuffer` Hello, world! "
  }
]
```
main.js is
```js
const options = {
  // isCaseSensitive: true,
  includeScore: true,
  // shouldSort: true,
  // includeMatches: true,
  // findAllMatches: true,
  // minMatchCharLength: 1,
  // location: 0,
  threshold: 0.9,
  distance: 5944,
  // useExtendedSearch: true,
  // ignoreLocation: true,
  // ignoreFieldNorm: true,
  keys: [
    "title",
    "author.firstName"
  ]
};

const fuse = new Fuse(list, options);

// Change the pattern
const pattern = "暂时"

return fuse.search(pattern)
```

both results are returned

**Comment by Shuliyey** [comment]
good morning @yihui 

i've tested the PR's change against below `_output.yaml`

```yaml
bookdown::gitbook:
  config:
    search:
      engine: fuse
```

was able to get positive results, although fuse.js have some fuzzy partial matching behaviours, this resulted in more returned results (i trid tuning with the options in https://fusejs.io/api/options.html, `threshold: 1` gave better returns, however there're still some partial matched page)

as an example https://fusejs.io/demo.html

list.json is
```json
[
  {
    "title": "5.2 2021-03-07 5.2.1 WSL (Windows Subsystem Linux) g++ protobuf (grpc) 编译问题 (undefined reference to “google::…”) 碰倒奇怪的g++ protobuf (grpc) 程序编译问题 g++ 版本 [甲] in ~ λ g++ --version g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 Copyright (C) 2019 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. protoc 版本 protobuffers_demo/src/cpp ▶ protoc --version libprotoc 3.6.1 编译报错 undefined reference to \google::protobuff::xxxx::…..’` # g++ [options] file... g++ -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer protobuffers_demo/src/cpp ▶ g++ -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer /usr/bin/ld: /tmp/cc8nNte2.o: in function `Company::set_name(char const*)&#39;: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x7d): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x202): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x211): undefined reference to `google::protobuf::internal::LogMessage::operator&lt;&lt;(char const*)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x21e): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&amp;)&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x226): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company8set_nameEPKc[_ZN7Company8set_nameEPKc]+0x2cd): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()&#39; /usr/bin/ld: /tmp/cc8nNte2.o: in function `Company::set_description(char const*)&#39;: create_protobuffer.cpp:(.text._ZN7Company15set_descriptionEPKc[_ZN7Company15set_descriptionEPKc]+0x7d): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]&#39; /usr/bin/ld: create_protobuffer.cpp:(.text._ZN7Company15set_descriptionEPKc[_ZN7Company15set_descriptionEPKc]+0x202): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)&#39; ... /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x60): undefined reference to `google::protobuf::Message::CheckTypeAndMergeFrom(google::protobuf::MessageLite const&amp;)&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0x80): undefined reference to `google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char*) const&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0xb0): undefined reference to `google::protobuf::Message::DiscardUnknownFields()&#39; /usr/bin/ld: company.pb.o:(.data.rel.ro._ZTV7Company[_ZTV7Company]+0xb8): undefined reference to `google::protobuf::Message::SpaceUsedLong() const&#39; /usr/bin/ld: company.pb.o:(.data.rel+0x10): undefined reference to `protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp&#39; collect2: error: ld returned 1 exit status 查询网络资料 https://zhuanlan.zhihu.com/p/305974542 提到 如果没有加上-lprotobuf 会报以下错误 project.pb.cc:(.text+0x5fc): undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)&#39; project.pb.cc:(.text+0x723): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)&#39; project.pb.cc:(.text+0x7b5): undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)&#39; project.pb.cc:(.text+0x849): undefined reference to `google::protobuf::internal::WireFormat::SkipField(google::protobuf::io::CodedInputStream*, unsigned int, google::protobuf::UnknownFieldSet*)&#39; /tmp/cc1U6w5J.o: In function `Account::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const&#39;: project.pb.cc:(.text+0x8eb): undefined reference to `google::protobuf::internal::WireFormatLite::WriteUInt64(int, unsigned long, google::protobuf::io::CodedOutputStream*) 可是 -lprotobuf 有作为参数传给 g++, 那么问题在哪呢，经过排查调整 g++ 参数顺序与位置的以下方法解决了问题 (暂时不清楚为何，大概率和g++ 处理参数顺序有关) g++ 参数顺序/位置调整: g++ [options] file... → g++ file... [options] # g++ file... [options] g++ create_protobuffer.cpp base64.o company.pb.o -o create_protobuffer -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread protobuffers_demo/src/cpp ▶ g++ base64.o company.pb.o create_protobuffer.cpp -o create_protobuffer -std=c++11 -Ofast -Iprotos -Ithird_parties/rapidjson/include -Ithird_parties -I/usr/local/include -pthread -L/usr/local/lib -lprotobuf -lpthread protobuffers_demo/src/cpp ▶ ls Makefile base64.o company.pb.o create_protobuffer create_protobuffer.cpp protos read_protobuffer.cpp third_parties"
  },
  {
    "title": " 5.3 2021-03-08 5.3.1 WSL (Windows Subsystem Linux) cargo 指令 file permission 报错 WSL 跑 cargo 指令时 (比如cargo build, cargo run) 碰到 file permission 报错 $ cargo build ... warning: Error finalizing incremental compilation session directory `/mnt/c/Users/zicog/conq-ws/target/debug/incremental/conq_ws_server-2q1bffu1vnc1a/s-fq0xl8u26v-4gktak-working`: Permission denied (os error 13) warning: 2 warnings emitted warning: Error finalizing incremental compilation session directory `/mnt/c/Users/zicog/conq-ws/target/debug/incremental/conq_ws_client_cli-nqj4wzo9q5jf/s-fq0xl8tdgv-vzck31-working`: Permission denied (os error 13) warning: 1 warning emitted Finished dev [unoptimized + debuginfo] target(s) in 0.26s 以上是此链接 https://users.rust-lang.org/t/strange-cargo-build-file-permission-warnings/46980 提到的报错 解决方案升级 WSL 到 WSL2 (官方文档 https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps) 后不再报错 自动升级 wsl --install 需要加入微软 Windows Insider Program, 这里简单讲解手动升级 确保 Microsoft-Windows-Subsystem-Linux VirtualMachinePlatform 已被启动 (跑dism 命令需以管理员身份跑) dism.exe /Online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux dism.exe /Online /Get-FeatureInfo /FeatureName:VirtualMachinePlatform 如看到 状态 : 已启用 相关信息则已被启用 (如下) PS C:\Users\老叶&gt; dism /Online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux 部署映像服务和管理工具 版本: 10.0.18362.1379 映像版本: 10.0.18363.1440 功能信息: 功能名称 : Microsoft-Windows-Subsystem-Linux 显示名称 : 适用于 Linux 的 Windows 子系统 描述 : 为 Windows 上运行的本机用户模式 Linux shell 和工具提供服务和环境。 需要重新启动 : Possible 状态 : 已启用 自定义属性: ServerComponent\Description : 提供服务和环境以在 Windows 上运行本机用户模式 Linux shell 和工具。 ServerComponent\DisplayName : 适用于 Linux 的 Windows 子系统 ServerComponent\Id : 1033 ServerComponent\Type : Feature ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux 操作成功完成。 PS C:\Users\老叶&gt; dism.exe /Online /Get-FeatureInfo /FeatureName:VirtualMachinePlatform 部署映像服务和管理工具 版本: 10.0.18362.1379 映像版本: 10.0.18363.1440 功能信息: 功能名称 : VirtualMachinePlatform 显示名称 : 虚拟机平台 描述 : 为虚拟机启用平台支持 需要重新启动 : Possible 状态 : 已启用 自定义属性: (没有找到任何自定义属性) 否则需启动 Microsoft-Windows-Subsystem-Linux VirtualMachinePlatform (注 VirtualMachinePlatform 需要在 BIOS 里启用 CPU VT-x 或相关类似虚拟功能 参考资料 https://techsviewer.com/enable-intel-virtualization-technology-vt-x-bios/) dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart 或者通过搜索 Windows Feature 启用 适用于 Linux 的 Windows 子系统 虚拟机平台 安装成功后重启系统 安装 WSL2 Linux Kernal 内核 下载地址 https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi Invoke-WebRequest https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi -OutFile $HOME\wsl_update_x64.msi msiexec /i $HOME\wsl_update_x64.msi /qf 设置默认 wsl 版本为2 wsl --set--default-version 2 新安装wsl Linux 版本 会默认为 WSL2, 以下讲解升级已安装 wsl 版本 到WSL2 检查已安装wsl, 这里需升级的 WSL 是 Ubuntu wsl -l -v PS C:\Users\老叶&gt; wsl -l -v NAME STATE VERSION * Ubuntu Running 1 设wsl Ubuntu 版本为2 (以下命令迁移过程会花些时间) wsl --set-version Ubuntu 2 再次检查 wsl Ubuntu 版本是否升级后为2 PS C:\Users\老叶&gt; wsl -l -v NAME STATE VERSION * Ubuntu Running 2 Alpine Running 2 登录 WSL2 Ubuntu, 再次尝试 cargo 相关指令 将不再有 file permission 相关报错 PS C:\Users\老叶&gt; wsl -d Ubuntu [oh-my-zsh] Random theme &#39;bira&#39; loaded ╭─xxx@xxx /mnt/c/Users/老叶 ╰─$ cd ╭─xxx@DY-PC ~ ╰─$ cd c++/protobuffers_demo/src/rust/read-protobuffer ╭─xxx@xxx ~/c++/protobuffers_demo/src/rust/read-protobuffer ‹master*› ╰─$ cargo run Finished dev [unoptimized + debuginfo] target(s) in 0.00s Running `target/debug/read-protobuffer` Hello, world! "
  }
]
```
main.js is
```js
const options = {
  // isCaseSensitive: true,
  includeScore: true,
  // shouldSort: true,
  // includeMatches: true,
  // findAllMatches: true,
  // minMatchCharLength: 1,
  // location: 0,
  threshold: 0.9,
  distance: 5944,
  // useExtendedSearch: true,
  // ignoreLocation: true,
  // ignoreFieldNorm: true,
  keys: [
    "title",
    "author.firstName"
  ]
};

const fuse = new Fuse(list, options);

// Change the pattern
const pattern = "暂时"

return fuse.search(pattern)
```

both results are returned (however `暂时` is only in the first list element), if i change the `pattern = ` to ` pattern = "暂"`, only one is returned (it feels like the longer the search strings are, the more likely partial matched pages will get higher `fuse` scores)

**Comment by yihui** [comment]
@Shuliyey Here is the config that I used before: https://github.com/yihui/hugo-prose/blob/16e041908e4d6a59e5c866d641d4787de88ec9b8/static/js/features.js#L297-L302 You may try it and see if it works better.

**Comment by Shuliyey** [comment]
> @Shuliyey Here is the config that I used before: https://github.com/yihui/hugo-prose/blob/16e041908e4d6a59e5c866d641d4787de88ec9b8/static/js/features.js#L297-L302 You may try it and see if it works better.

cheers yihui, it worked 😄 , so threshold is the tolerance of partial match, `0` means it must be exact match, `ignoreLocation` = `true` is the key here, it means the match can start anywhere in the string, i see how this worked now, i've pushed new changes (threshold i set default to `0.1`, i can confirm `0` is more stricter for exact match)

**Review by yihui — APPROVED** [review]
Looks great. I'll tweak it and merge later. Thank you!

**Pull request merged**
